### ISSUE TITLE
How to get column data in formatter ?

### ISSUE THREAD

**Issue by NishantDesai1306** [kagawagao/json-csv-transformer#1]
Is there a way to get column data along with that fields data ?

```
{
  key: 'someField',
  label: 'Field',
  formatter: {
    csv: function (fieldValue, rowData) => {}
  }
}
```

**Comment by kagawagao** [comment]
feature has been done in 24a599705ebb1c188fe2e32812f103a881d3cc88, the third parameter is the row data
